---
name: ðŸ“¦ CI

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
     - main
  workflow_dispatch:

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    env:
      PIPENV_VENV_IN_PROJECT: true
    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '{{ project.python_version }}'

      - name: Install pipenv
        run: |
          pip -V
          python -m pip install --upgrade pipenv wheel

      - name: Cache pipenv
        id: cache-pipenv
        uses: actions/cache@v2.1.7
        with:
          #path: ~/.local/share/virtualenvs
          path: .venv
          key: ${{ runner.os }}-pipenv-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-

      - name: Install all dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --deploy --dev

      - name: Run linter
        run: make lint

      - name: Run the tests
        run: make test

      - name: Automerge PR
        run: >-
          gh pr merge --auto --merge --delete-branch ${{ github.event.pull_request.number }}
        env:
          # If using the default ${{secrets.GITHUB_TOKEN}} merge works but branch is not deleted
          # had to use a Personal Access Token with full "repo" permissions
          # See https://github.com/cli/cli/issues/3884#issuecomment-868860269
          GITHUB_TOKEN: ${{ secrets.PAT_REPO_FULL }}
